# Generated by Django 4.1 on 2023-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_products_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.CharField(choices=[('cement', 'cement'), ('rods', 'rods'), ('others', 'others')], max_length=100),
        ),
    ]
